CONFIG_H_PATH = "CONFIG_H_PATH"
PROJECT_NAME = "PROJECT_NAME"
PROJECT_VERSION = "PROJECT_VERSION"
LLM_URL = "LLM_URL"
LLM_MODEL_NAME = "LLM_MODEL_NAME"
LLM_API_KEY = "LLM_API_KEY"
LOG_FILE = "LOG_FILE"
DOWNLOAD_REPO = "DOWNLOAD_REPO"
DEBUG_MODULES = "DEBUG_MODULES"
REPO_REMOTE_URL = "REPO_REMOTE_URL"
REPO_LOCAL_PATH = "REPO_LOCAL_PATH"
EMBEDDINGS_LLM_URL = "EMBEDDINGS_LLM_URL"
EMBEDDINGS_LLM_API_KEY = "EMBEDDINGS_LLM_API_KEY"
EMBEDDINGS_LLM_MODEL_NAME = "EMBEDDINGS_LLM_MODEL_NAME"
OUTPUT_FILE_PATH = "OUTPUT_FILE_PATH"
AGGREGATE_RESULTS_G_SHEET = "AGGREGATE_RESULTS_G_SHEET"
INPUT_REPORT_FILE_PATH = "INPUT_REPORT_FILE_PATH"
KNOWN_FALSE_POSITIVE_FILE_PATH = "KNOWN_FALSE_POSITIVE_FILE_PATH"
HUMAN_VERIFIED_FILE_PATH = "HUMAN_VERIFIED_FILE_PATH"
USE_KNOWN_FALSE_POSITIVE_FILE = "USE_KNOWN_FALSE_POSITIVE_FILE"
CALCULATE_METRICS = "CALCULATE_METRICS"
TOKENIZERS_PARALLELISM = "TOKENIZERS_PARALLELISM"
RUN_WITH_CRITIQUE = "RUN_WITH_CRITIQUE"
CRITIQUE_LLM_URL = "CRITIQUE_LLM_URL"
CRITIQUE_LLM_MODEL_NAME = "CRITIQUE_LLM_MODEL_NAME"
CRITIQUE_LLM_API_KEY = "CRITIQUE_LLM_API_KEY"
SERVICE_ACCOUNT_JSON_PATH = "SERVICE_ACCOUNT_JSON_PATH"
RED_ERROR_FOR_LLM_REQUEST = (
    "WARNING: An error occurred "
    "{max_retry_limit} times in {function_name} process. "
    "Please check this Issue-id {issue_id}."
    "\nError: {error}"
)
FALLBACK_JUSTIFICATION_MESSAGE = [
    "Failed during analyze process. Defaulting to: NOT A FALSE POSITIVE."
]
YES_OPTIONS = ["y", "yes"]
NO_OPTIONS = ["n", "no"]
ALL_VALID_OPTIONS = YES_OPTIONS + NO_OPTIONS
